### ISSUE TITLE
setup script messes up system permissions

### ISSUE THREAD

**Issue by pierinz** [rsm-gh/alienware-kbl#27]
The setup script overwrites the /usr/bin/, /usr/share/, /usr/share/doc, /usr/lib/, /usr/lib/systemd/, /usr/lib/systemd/system/ folders, leaving them with the wrong owner, group and permissions.
If you extract the zip archive with 7-zip the system can't boot anymore because the default directory permissions are 0700 instead of 0755.

Please use the "install" command instead of "cp -ar" and "chmod".

**Comment by rsm-gh** [comment]
It would be nice if you commit this, its an important bug. I tried to fix it in the past but I ignore why my solution didn't worked !
