### ISSUE TITLE
Theme Module not found

### ISSUE THREAD

**Issue by AamerShareef** [rsm-gh/alienware-kbl#28]
On running alienware-kbl from the terminal, I get an error message saying cannot import Theme module.

**Comment by rsm-gh** [comment]
Are you using the stable version?

**Comment by AamerShareef** [comment]
never mind. It worked after reinstalling. You can mark this as closed. thanks!

**Comment by rsm-gh** [comment]
Okay, anyways this is also fixed in the new killer version that will be released soon.    

Regards ! rsm
