### ISSUE TITLE
Alienware 13 (r1)

### ISSUE THREAD

**Issue by buzyn** [rsm-gh/alienware-kbl#36]
Выставил белый цвет везде! (правый центр клавиатуры слабо подсвечен или вообще не подсвечен)

начинаю тестировать и выбираю изменяющийся режим подсветки. Белый + красный

Центр-право - (изменяющийся справа) изменяется зарядка на кнопке включения. Когда включаю мигающий слева - хаотичность из красного синего и белого, но когда меняю справа налево синего цвета незаметно.

Head - при выборе крассного цвета полного или изменяющего (белый + крассный) - ничего не происходит.
Logo - при выборе белого + крассного цвета - меняются (но самого красного насыщщеного цвета нет)
Caps lock - на моем ноутбуке alienware 13 - hdd, bluetooth/(wlan), caps lock изменяют цвет одновременно по схеме microsoft. По вашей схеме capslock-bluetooth/(wlan) вместе! Hdd не меняется
Hard Disk Drive - при выборе белого + крассного цвета все работатет как и Logo - без крассного насыщщенного
Keyboard left centr - при выборе белого + крассного цвета все работатет как и Logo - без крассного насыщщенного
Keyboard left -  при выборе белого + крассного цвета все работатет как и Logo - без крассного насыщщенного
Outer lid - при выборе белого + крассного цвета все работатет как и Logo - без крассного насыщщенного
Keyboard right centr - (изменяющийся справа) изменяется зарядка на кнопке включения. Когда включаю мигающий слева - хаотичность из красного синего и белого, но когда меняю справа налево синего цвета незаметно.
Keyboard ight - при выборе белого + крассного цвета все работатет как и Logo - без крассного насыщщенного

Замеченные мною отклонения в калибровке цветов и управлении логтипом под дисплеем. 
Я выбрал белый цвет подсветки всех элементов. Элементы logo hdd capslock wlan head - имеют желтый оттенок. (возможно это имеет другой тип led в заводской конструкции, в официальной версии под microsoft - нет выбора белого цвета вовсе)

Лого в виде надписи alienware которое находится под дисплеем буду назывть LOGO

Дальше я начал искать HEAD, ведь я зменил все цвета изначально.
Устанавливал белый+крассный, крассный+белый, крассный+крассный : ничего не менялось! Поставил на нем Черный! Возможно гдето чтото потухнет

Ищу дальше и перехожу к Logo - выставляю крассный + белый - начинает изменяться цвет LOGO под дисплеем! (примерно так : белый + голубой + красный)
выставляю крассный + крассный  - Logo светится крассным цветом, стабильно! (но не насыщщено - ярко морковный)

Преешел к outer lid - выставил зеленый + желтый - изменяется! К этому времени ноут полностью заряжен! И при отключении зарядного, кнопка включения в виде головы загорелась зеленым!, при подключении зарядного - кнопка мигает зеленым + желтым, как и наружный логотип на крышке экрана. Аккумулятор зарядился - head светится белым.

Keyboard right centre выставил крассный + белый! На клавиатуре не изменилось ничего, но Head начал менять цвета (красный-белый-голубой и подмигивает желтым) изменил вариант: белый+крассный (меняет цвета нормально - не подмигивает желтым) но все же должен управлять правым центром, а не head.
Выставил везде черный цвет. Все потухло.! 
Keyboard right centre выставил крассный + белый. Погулялся ползунком скорости изменения цветов.
Когда на минимум - крассный, желтый мигает, голубой, белый.
Когда на максимум, все очень плавно - но слишком много ненужных цветов от крассного до белого (хотя я допускаю конструктивную особенность невозможности переключения цветов от крассного к розовому и к белому.)

Выставил все крассное - Head оставил черным.
Но кнопка включения\выключения в виде головы светится крассным и подмигивает желтым.

Вот такой хаос происходит.
Новую стабильную версию не получилось запустить. Пришлось скачать старую, запустить старую, потом сверху установить новую. Но ничего стабильного для моего Alienware 13 не получилось.

**Comment by buzyn** [comment]
возможно отклонение в наблюдениях заряда батареи. Только заметил, дебиан  показывает 98% заряда, до полного заряда - еще 2 часа :-( (батарея к сожалению уже не идеальна)

**Comment by buzyn** [comment]
╭─root@debian /home/user  
╰─➤  alienware-kbl --start-daemon
DEBUG from `/usr/share/AlienwareKBL/Engine/Core/Driver.py` on method `find_device`:
DEVICE ID 187c:0527 on Bus 002 Address 004 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :    0x2 USB 0.02
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x187c
 idProduct              : 0x0527
 bcdDevice              :    0x0 Device 0.0
 iManufacturer          :    0x1 Alienware
 iProduct               :    0x2 AW13
 iSerialNumber          :    0x3 13.0
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x29 (41 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xe0 Self Powered, Remote Wakeup
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0xa (10 bytes)
       bInterval        :    0xa


DEBUG from `/usr/share/AlienwareKBL/Engine/Core/Driver.py` on method `find_device`:
BLOCK_LOAD_ON_BOOT=1
COMMAND_SAVE_NEXT=8
REGION_OUTER_LID=32
BLOCK_BATT_CRITICAL=9
REGION_CAPS_LOCK=128
REGION_RIGHT_KEYBOARD=1
RESET_ALL_LIGHTS_OFF=3
REGION_ALL_BUT_POWER=1023999
COMMAND_SET_COLOR=3
COMMAND_TRANSMIT_EXECUTE=5
RESET_TOUCH_CONTROLS=1
FILL_BYTE=0
REGION_LEFT_CENTER_KEYBOARD=4
BLOCK_BATT_SLEEPING=7
DEFAULT_MODE=fixed
DEFAULT_SPEED=255
REGION_HARD_DISK_DRIVE=512
BLOCK_BAT_POWER=8
COMMAND_SAVE=9
COMMAND_SET_BLINK_COLOR=2
COMMAND_LOOP_BLOCK_END=4
DATA_LENGTH=9
REGION_ALIENWARE_NAME=64
COMMAND_SET_SPEED=14
STATE_BUSY=17
VENDOR_ID=6268
SUPPORTED_COMMANDS=15
RESET_SLEEP_LIGHTS_ON=2
REGION_LEFT_KEYBOARD=8
RESET_ALL_LIGHTS_ON=4
COMMAND_GET_STATUS=6
BLOCK_AC_POWER=5
COMMAND_RESET=7
STATE_READY=16
START_BYTE=2
BLOCK_STANDBY=2
COMMAND_END_STORAGE=0
DEFAULT_COLOR=#0000FF
COMMAND_SET_MORPH_COLOR=1
NAME=Alienware13
STATE_UNKNOWN_COMMAND=18
REGION_RIGHT_CENTER_KEYBOARD=256
COMMAND_BATTERY_STATE=15
PRODUCT_ID=1319
BLOCK_CHARGING=6
REGION_ALIENWARE_HEAD=256
regions:

    name=CL
    description=Caps Lock
    hex_id=128
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=HDD
    description=Hard Disk Drive
    hex_id=512
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=AH
    description=Head
    hex_id=256
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=LK
    description=Keyboard: Left 
    hex_id=8
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=LCK
    description=Keyboard: Left-Center
    hex_id=4
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=RCK
    description=Keyboard: Righ-Center
    hex_id=256
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=RCK
    description=Keyboard: Righ-Center
    hex_id=256
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=RK
    description=Keyboard: Right
    hex_id=1
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=AL
    description=Logo
    hex_id=64
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


    name=OI
    description=Outer Lid
    hex_id=32
    can_light=True
    can_blink=True
    can_morph=True
    max_comands=15


DEBUG from `/usr/share/AlienwareKBL/Configuration/Theme.py` on method `load`:
path=`/root/.local/share/alienware-kbl/Default.cfg`


DEBUG from `/usr/share/AlienwareKBL/Configuration/Theme.py` on method `load`:
#############################################
##### Alienware-KBL configuration theme #####
#############################################

name=Default
speed=255


********************************************
area=AH


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=AL


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=CL


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=HDD


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=LCK


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=LK


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=OI


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=RCK


mode=fixed
left_color=#0000FF
right_color=#0000FF

********************************************
area=RK


mode=fixed
left_color=#0000FF
right_color=#0000FF

**Comment by buzyn** [comment]
Dected As: Alienware13
 Vendor ID: 6268
 Product ID: 1319

DEVICE ID 187c:0527 on Bus 002 Address 004 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :    0x2 USB 0.02
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x187c
 idProduct              : 0x0527
 bcdDevice              :    0x0 Device 0.0
 iManufacturer          :    0x1 Alienware
 iProduct               :    0x2 AW13
 iSerialNumber          :    0x3 13.0
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x29 (41 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xe0 Self Powered, Remote Wakeup
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0xa (10 bytes)
       bInterval        :    0xa

**Comment by rsm-gh** [comment]
Hi, you want support please write in English. Use google translate or something...

**Comment by buzyn** [comment]
https://youtu.be/84HCjTYMPWg  video test

**Comment by buzyn** [comment]
I want to help all those in need of setting up this model.
what commands should I enter?
I will enter all the teams, and finish here. I can record video and throw it in YouTube.
I think you need to check the version of the python and other packages for the concept.
I already managed to launch the kubuntu 17.04

**Comment by buzyn** [comment]
downloaded the old version. launched the test unit.
White is selected for the test.
The backlight of the keyboard consists of four zones.
[TEST]: block: 1	 hex: 0x1	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff            right
[TEST]: block: 2	 hex: 0x2	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff            centr-right
[TEST]: block: 4	 hex: 0x4	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff            centr-left
[TEST]: block: 8	 hex: 0x8	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff            left

[TEST]: block: 32	 hex: 0x20	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff    out lid
[TEST]: block: 64	 hex: 0x40	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff    logo (bottom of the display)


[TEST]: block: 128	 hex: 0x80	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff     bluetooth(wifi)/caps lock
perhaps this description is important!
backlight bluetooth and wifi in one block, lights up only when installing the bluetooth driver. caps lock changes color together with bluetooth / wifi. but activated separately when you press the appropriate key.

[TEST]: block: 512	 hex: 0x200	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff     hdd

[TEST]: block: 256	 hex: 0x100	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff    head (power button)
The head has several glow modes in ms win. With a charged battery, a constant glow, with a charging battery, a changing color. when there is a strong discharge, active flicker. At work from the accumulator other color. (I'll show you later the video, if necessary)



[TEST]: block: 1048476	 hex: 0xfff9c	 mode:morph	 speed:1	 color1:#ffffff	 color2: #ffffff    
this unit included head, hdd, capslock, left keyboard, centr left keyboard

**Comment by buzyn** [comment]
https://youtu.be/8G6TjjK7DcY  illumination hdd, bt\wlan, capslock

**Comment by rsm-gh** [comment]
Thanks for all your information, I've made [a commit](https://github.com/rsm-gh/alienware-kbl/commit/21b014c12e7d7776a9489b071d0e6c45e9581639) to add your improvements.

Concerning the old configuration only the `REGION_RIGHT_CENTER_KEYBOARD` changed (I didn't added the new section `block=1048476 # head, hdd, CapsLock, Left keyboard, Center Left Keyboard` zone).

Could you download the stable branch and confirm that everything is okay? Just take care of using as root `rm -rf /usr/share/AlienwareKBL` before re-installing the software. I think sometimes the installation is not removing all the previous code...

Regards 
rsm

**Comment by buzyn** [comment]
the latest version of alienware-kbl is installed on a new kubuntu 17.04
https://youtu.be/FCSV0cso8cA video test

**Comment by buzyn** [comment]
the latest version of alienware-kbl is installed on a new kubuntu 17.04
https://youtu.be/FCSV0cso8cA video test

**Comment by buzyn** [comment]
the latest version of alienware-kbl is installed on a new kubuntu 17.04
https://youtu.be/FCSV0cso8cA video test

**Comment by buzyn** [comment]
I think the problem is in the graphical environment of the program. earlier in one compartment you could choose 2 colors. now I can not do this. Several times I noticed that the brightness of the keyboard on the right was changing, as if there was not enough voltage on the LEDs (perhaps in the official program the synchronization of the illumination excludes this phenomenon). How can I increase or decrease the brightness of the backlight? The activity slider muted changes the rate of color substitution.
I can think a lot about it, but it would be nice to add the ability to change the brightness of the backlight with a slider for each block, the color replacement time in each block, and the illumination alert that is activated from the instant messages of the system. 
p.s. Thank you for your help and updates in the development. Best regards, Artem.

**Comment by rsm-gh** [comment]
To choose two colors you must select the "morph" mode:
![screenshot_2017-11-17_19-58-14](https://user-images.githubusercontent.com/11134652/32963938-dbe34808-cbd1-11e7-9855-382ba3473fdf.png)
Or add another zone:
![screenshot_2017-11-17_20-00-35](https://user-images.githubusercontent.com/11134652/32964014-11bfa1f6-cbd2-11e7-9a24-78a43a12aa54.png)

After seeing the video, I noticed that you're experiencing the [Ubuntu problems](https://github.com/rsm-gh/alienware-kbl/issues/15) (since Kubuntu is ubuntu based).

I'll try to fix that as soon as possible since that's a critical Ubuntu bug.

And about the brightness, well, I have no Idea of how to do that, probably the bock numbers that we use on linux are not 100% accurate, but as far as I know the pyAlienFx team contacted Alienware to get support and they didn't answer.

Anyways thanks for pointing all those problems and if you have more remarks don't hesitate to comment.

Regards,
rsm

**Comment by buzyn** [comment]
installed. manjaro. the shell is normal. control has become much more convenient. but Head control does not work. Shines yellow when selecting any of the colors.

(manjaro is a pretty good system, it seems to me that it works more stable than ubuntu, but I can not start bluetooth, logitech mx master becomes useless mice. :-(  )

**Comment by buzyn** [comment]
I just noticed an interesting moment. tested the HEAD illumination. chose black color, after loading another operating system returned back to the manjaro the backlight of all the blocks is completely off. launched alienware-kbl head color selected black from past test. switched on the backlight. head does not glow, logo does not glow, I choose the color head. now head changes color yellow-red, logo turned on as red as it should be!
