### ISSUE TITLE
Add support for MacOS 

### ISSUE THREAD

**Issue by RockJesus** [rsm-gh/alienware-kbl#37]
Alienware 17 R4（Windows10+MacOS High Sierra 10.13+PhoenixOS） CPU:i7-7700hq-RAM:16g-GFX:HD630/Nv 1060-SAT:m.2 128G/1T-AU:ALC298-NET:KILLER E2500

 HID aw1517 DEVICE ID 187c:0530

Keyboard backlight working good but conld not change colors on MacOS 10.13.3

**Comment by rsm-gh** [comment]
I'm sorry but that will not happen in my code !
