### ISSUE TITLE
usb.core.USBError: [Errno 75] Overflow

### ISSUE THREAD

**Issue by wanjizheng** [rsm-gh/alienware-kbl#42]
Installed Ubuntu 18.04 on my Alienware 15 R3, but cannot make this to work.
Device information:

Device: ID 187c:0530 Alienware Corporation 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0530 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW1517
  iSerial                 3 03.00
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
          Report Descriptor: (length is 56)
            Item(Global): Usage Page, data= [ 0x00 0xff ] 65280
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Usage Page, data= [ 0x0c ] 12
                            Consumer
            Item(Local ): Usage, data= [ 0x06 ] 6
                            (null)
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x00 ] 0
                            Unassigned
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            Still
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x14 ] 20
                            Alphanumeric Display
            Item(Local ): Usage, data= [ 0x2b ] 43
                            Character Report
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Alphanumeric Display
            Item(Local ): Usage Maximum, data= [ 0x66 ] 102
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x0b ] 11
            Item(Local ): Usage, data= [ 0x2c ] 44
                            Display Data
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10================================
Device Status:     0x0000
  (Bus Powered)

**Log during the block testing:**

[Device found]: Vendor ID: 6268	 Product ID: 1328

Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/BlockTesting/BlockTesting.py", line 335, in on_button_block_testing_lights_off_clicked
    self._testing_controller.add_reset_line(self._computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 77, in add_reset_line
    while not self._device_is_ready():
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 48, in _device_is_ready
    msg = self._driver.read_device(constructor)
  File "/usr/share/AlienwareKBL/Engine/Core/Driver.py", line 107, in read_device
    msg = self._device.ctrl_transfer(self.READ_REQUEST_TYPE, self.READ_REQUEST, self.READ_VALUE, self.READ_INDEX, len(msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
[TEST]: block: 1	 hex: 0x1	 mode:blink	 speed:1	 color1:#204a87	 color2: #204a87

Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/BlockTesting/BlockTesting.py", line 316, in on_button_block_make_test_clicked
    self._testing_controller.add_reset_line(self._computer.RESET_ALL_LIGHTS_ON)
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 77, in add_reset_line
    while not self._device_is_ready():
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 48, in _device_is_ready
    msg = self._driver.read_device(constructor)
  File "/usr/share/AlienwareKBL/Engine/Core/Driver.py", line 107, in read_device
    msg = self._device.ctrl_transfer(self.READ_REQUEST_TYPE, self.READ_REQUEST, self.READ_VALUE, self.READ_INDEX, len(msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow

Anyone can help with this?

**Comment by rsm-gh** [comment]
Duplicated of "[Add support to the Alienware 13 R3 computer](https://github.com/rsm-gh/alienware-kbl/issues/8)".
