### ISSUE TITLE
Python-Pyro @expose

### ISSUE THREAD

**Issue by anees042** [rsm-gh/alienware-kbl#9]
Python bindings giving the following error, Alienware 17 R3. 
```
File "/usr/share/alienware-kbl/Daemon.py", line 47, in <module>
    class Daemon:
  File "/usr/share/alienware-kbl/Daemon.py", line 130, in Daemon
    @Pyro4.expose
AttributeError: module 'Pyro4' has no attribute 'expose'
```

**Comment by rsm-gh** [comment]
Hi, 
You are having that problem because you are using an older version of Pyro. What distribution are you using?

**Comment by anees042** [comment]
i followed the installation instructions. it's ubuntu 16.04

**Comment by rsm-gh** [comment]
The decorator is missing because you are using an older version python-pyro. I think that if you delete python-pyro and you install it trough pip `apt-get install pip3 && pip3 install pyro` it should do the trick.

**Comment by anees042** [comment]
it works now, thanks for the info.
